### ISSUE TITLE
Rebake Error

### ISSUE THREAD

**Issue by Mondrethos** [RpNation/bbcode#102]
```
Failed to rebake (topic_id: 93, post_id: 160)
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
JavaScript at fenceCodeBlockPreprocess (<anonymous>:2371:52)
JavaScript at preprocessRaw (<anonymous>:2400:23)
JavaScript at RpNBBCode (<anonymous>:2421:48)
JavaScript at preprocessor (discourse/plugins/bbcode/lib/discourse-markdown/bbcode-plugin:23:23)
JavaScript at engine.render (discourse/plugins/bbcode/lib/discourse-markdown/bbcode-plugin:67:42)
JavaScript at cook (discourse-markdown-it/engine:58:37)
JavaScript at DiscourseMarkdownIt.cook (discourse-markdown-it/index:55:33)
JavaScript at <anonymous>:1:6
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/mini_racer-0.9.0/lib/mini_racer.rb:228:in `eval_unsafe'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/mini_racer-0.9.0/lib/mini_racer.rb:228:in `block (2 levels) in eval'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/mini_racer-0.9.0/lib/mini_racer.rb:369:in `timeout'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/mini_racer-0.9.0/lib/mini_racer.rb:227:in `block in eval'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/mini_racer-0.9.0/lib/mini_racer.rb:225:in `synchronize'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/mini_racer-0.9.0/lib/mini_racer.rb:225:in `eval'
/var/www/discourse/lib/pretty_text.rb:236:in `block in markdown'
/var/www/discourse/lib/pretty_text.rb:676:in `block in protect'
/var/www/discourse/lib/pretty_text.rb:676:in `synchronize'
/var/www/discourse/lib/pretty_text.rb:676:in `protect'
/var/www/discourse/lib/pretty_text.rb:174:in `markdown'
/var/www/discourse/lib/pretty_text.rb:299:in `cook'
/var/www/discourse/app/models/post_analyzer.rb:30:in `cook'
/var/www/discourse/app/models/post.rb:347:in `cook'
/var/www/discourse/app/models/post.rb:778:in `rebake!'
/var/www/discourse/lib/tasks/posts.rake:145:in `rebake_post'
/var/www/discourse/lib/tasks/posts.rake:132:in `block (2 levels) in rebake_posts'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/relation/delegation.rb:88:in `each'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/relation/delegation.rb:88:in `each'
/var/www/discourse/lib/tasks/posts.rake:131:in `block in rebake_posts'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/core_ext/range/each.rb:14:in `step'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/core_ext/range/each.rb:14:in `step'
/var/www/discourse/lib/tasks/posts.rake:126:in `rebake_posts'
/var/www/discourse/lib/tasks/posts.rake:111:in `block in rebake_posts_all_sites'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rails_multisite-6.0.0/lib/rails_multisite/connection_management/null_instance.rb:49:in `with_connection'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rails_multisite-6.0.0/lib/rails_multisite/connection_management/null_instance.rb:36:in `each_connection'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rails_multisite-6.0.0/lib/rails_multisite/connection_management.rb:21:in `each_connection'
/var/www/discourse/lib/tasks/posts.rake:111:in `rebake_posts_all_sites'
/var/www/discourse/lib/tasks/posts.rake:7:in `block in <main>'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:188:in `invoke_task'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `each'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block in top_level'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:147:in `run_with_threads'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:132:in `top_level'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:83:in `block in run'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:80:in `run'
bin/rake:13:in `<top (required)>'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli.rb:451:in `exec'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli.rb:28:in `start'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/exe/bundle:28:in `block in <top (required)>'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/exe/bundle:20:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
      246 / 356 ( 69.1%)
Failed to rebake (topic_id: 64, post_id: 111)
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
JavaScript at fenceCodeBlockPreprocess (<anonymous>:2371:52)
JavaScript at preprocessRaw (<anonymous>:2400:23)
JavaScript at RpNBBCode (<anonymous>:2421:48)
JavaScript at preprocessor (discourse/plugins/bbcode/lib/discourse-markdown/bbcode-plugin:23:23)
JavaScript at engine.render (discourse/plugins/bbcode/lib/discourse-markdown/bbcode-plugin:67:42)
JavaScript at cook (discourse-markdown-it/engine:58:37)
JavaScript at DiscourseMarkdownIt.cook (discourse-markdown-it/index:55:33)
JavaScript at <anonymous>:1:6
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/mini_racer-0.9.0/lib/mini_racer.rb:228:in `eval_unsafe'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/mini_racer-0.9.0/lib/mini_racer.rb:228:in `block (2 levels) in eval'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/mini_racer-0.9.0/lib/mini_racer.rb:369:in `timeout'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/mini_racer-0.9.0/lib/mini_racer.rb:227:in `block in eval'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/mini_racer-0.9.0/lib/mini_racer.rb:225:in `synchronize'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/mini_racer-0.9.0/lib/mini_racer.rb:225:in `eval'
/var/www/discourse/lib/pretty_text.rb:236:in `block in markdown'
/var/www/discourse/lib/pretty_text.rb:676:in `block in protect'
/var/www/discourse/lib/pretty_text.rb:676:in `synchronize'
/var/www/discourse/lib/pretty_text.rb:676:in `protect'
/var/www/discourse/lib/pretty_text.rb:174:in `markdown'
/var/www/discourse/lib/pretty_text.rb:299:in `cook'
/var/www/discourse/app/models/post_analyzer.rb:30:in `cook'
/var/www/discourse/app/models/post.rb:347:in `cook'
/var/www/discourse/app/models/post.rb:778:in `rebake!'
/var/www/discourse/lib/tasks/posts.rake:145:in `rebake_post'
/var/www/discourse/lib/tasks/posts.rake:132:in `block (2 levels) in rebake_posts'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/relation/delegation.rb:88:in `each'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/relation/delegation.rb:88:in `each'
/var/www/discourse/lib/tasks/posts.rake:131:in `block in rebake_posts'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/core_ext/range/each.rb:14:in `step'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/core_ext/range/each.rb:14:in `step'
/var/www/discourse/lib/tasks/posts.rake:126:in `rebake_posts'
/var/www/discourse/lib/tasks/posts.rake:111:in `block in rebake_posts_all_sites'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rails_multisite-6.0.0/lib/rails_multisite/connection_management/null_instance.rb:49:in `with_connection'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rails_multisite-6.0.0/lib/rails_multisite/connection_management/null_instance.rb:36:in `each_connection'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rails_multisite-6.0.0/lib/rails_multisite/connection_management.rb:21:in `each_connection'
/var/www/discourse/lib/tasks/posts.rake:111:in `rebake_posts_all_sites'
/var/www/discourse/lib/tasks/posts.rake:7:in `block in <main>'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:188:in `invoke_task'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `each'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block in top_level'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:147:in `run_with_threads'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:132:in `top_level'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:83:in `block in run'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:80:in `run'
bin/rake:13:in `<top (required)>'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli.rb:451:in `exec'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli.rb:28:in `start'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/exe/bundle:28:in `block in <top (required)>'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/exe/bundle:20:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
      249 / 356 ( 69.9%)
Failed to rebake (topic_id: 64, post_id: 108)
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
JavaScript at fenceCodeBlockPreprocess (<anonymous>:2371:52)
JavaScript at preprocessRaw (<anonymous>:2400:23)
JavaScript at RpNBBCode (<anonymous>:2421:48)
JavaScript at preprocessor (discourse/plugins/bbcode/lib/discourse-markdown/bbcode-plugin:23:23)
JavaScript at engine.render (discourse/plugins/bbcode/lib/discourse-markdown/bbcode-plugin:67:42)
JavaScript at cook (discourse-markdown-it/engine:58:37)
JavaScript at DiscourseMarkdownIt.cook (discourse-markdown-it/index:55:33)
JavaScript at <anonymous>:1:6
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/mini_racer-0.9.0/lib/mini_racer.rb:228:in `eval_unsafe'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/mini_racer-0.9.0/lib/mini_racer.rb:228:in `block (2 levels) in eval'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/mini_racer-0.9.0/lib/mini_racer.rb:369:in `timeout'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/mini_racer-0.9.0/lib/mini_racer.rb:227:in `block in eval'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/mini_racer-0.9.0/lib/mini_racer.rb:225:in `synchronize'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/mini_racer-0.9.0/lib/mini_racer.rb:225:in `eval'
/var/www/discourse/lib/pretty_text.rb:236:in `block in markdown'
/var/www/discourse/lib/pretty_text.rb:676:in `block in protect'
/var/www/discourse/lib/pretty_text.rb:676:in `synchronize'
/var/www/discourse/lib/pretty_text.rb:676:in `protect'
/var/www/discourse/lib/pretty_text.rb:174:in `markdown'
/var/www/discourse/lib/pretty_text.rb:299:in `cook'
/var/www/discourse/app/models/post_analyzer.rb:30:in `cook'
/var/www/discourse/app/models/post.rb:347:in `cook'
/var/www/discourse/app/models/post.rb:778:in `rebake!'
/var/www/discourse/lib/tasks/posts.rake:145:in `rebake_post'
/var/www/discourse/lib/tasks/posts.rake:132:in `block (2 levels) in rebake_posts'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/relation/delegation.rb:88:in `each'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/relation/delegation.rb:88:in `each'
/var/www/discourse/lib/tasks/posts.rake:131:in `block in rebake_posts'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/core_ext/range/each.rb:14:in `step'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/core_ext/range/each.rb:14:in `step'
/var/www/discourse/lib/tasks/posts.rake:126:in `rebake_posts'
/var/www/discourse/lib/tasks/posts.rake:111:in `block in rebake_posts_all_sites'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rails_multisite-6.0.0/lib/rails_multisite/connection_management/null_instance.rb:49:in `with_connection'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rails_multisite-6.0.0/lib/rails_multisite/connection_management/null_instance.rb:36:in `each_connection'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rails_multisite-6.0.0/lib/rails_multisite/connection_management.rb:21:in `each_connection'
/var/www/discourse/lib/tasks/posts.rake:111:in `rebake_posts_all_sites'
/var/www/discourse/lib/tasks/posts.rake:7:in `block in <main>'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:188:in `invoke_task'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `each'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block in top_level'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:147:in `run_with_threads'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:132:in `top_level'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:83:in `block in run'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
/var/www/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:80:in `run'
bin/rake:13:in `<top (required)>'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli.rb:451:in `exec'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli.rb:28:in `start'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/exe/bundle:28:in `block in <top (required)>'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/exe/bundle:20:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
      356 / 356 (100.0%)
356 posts done!
```

**Comment by Mondrethos** [comment]
The error seems to be post 9 in the guide: https://t.rpnation.com/t/rpnation-bbcode-guide/129/9

**Comment by blythechan** [comment]
From testing, even bold bb triggered this error.
![image](https://github.com/RpNation/bbcode/assets/55112994/752a59d7-f32d-44eb-a54e-aea78093bc15)
Generated when code ticks were in play for any implemented bbcode. Code ticks were hitting a condition where logic attempted to create a bbcode tag.
